input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane

automation:
  - alias: Turn on Lounge Lamp at sunset
    trigger:
      - platform: sun
        event: 'sunset'
        offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.loungelamp
  - alias: Turn off Lounge Lamp at bedtime
    trigger:
      - platform: time
        at: '23:25'
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.loungelamp
